# Basic App Info
spring.application.name=user-service
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/quantity_db
spring.datasource.username=root
spring.datasource.password=Ravi@ku123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Logging
logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG

# Disable default UserDetailsService password log
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# JWT
jwt.expiration=86400000

# OAuth2 post-login redirect (your frontend callback)
app.oauth2.redirect-uri=http://localhost:5173/oauth/callback

# Frontend URL
app.frontend.url=http://localhost:5173

# Actuator
management.endpoints.web.exposure.include=health,metrics

# Swagger
springdoc.swagger-ui.enabled=true

spring.config.import=optional:classpath:application-secrets.properties

# ========== GOOGLE OAUTH2 ==========
spring.security.oauth2.client.registration.google.client-id=491908488436-j6lo7c4u7sdckp4nhbu19ktb7i1ag5ud.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# ========== GITHUB OAUTH2 ==========
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
spring.security.oauth2.client.registration.github.client-id=Ov23lifHCQNkTLXBw7Di
spring.security.oauth2.client.registration.github.client-secret=816274fbfd57af908b04c8ea4c60325830a47aa7
spring.security.oauth2.client.registration.github.scope=read:user,user:email
